---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kinto
  labels:
    app: ${PROJECT}
    component: kinto
    namespace: ${PROJECT}-${BRANCH_HASH}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${PROJECT}
        component: kinto
        namespace: ${PROJECT}-${BRANCH_HASH}
    spec:
      containers:
      - name: kinto
        image: kinto/kinto-server:${KINTO_VERSION}
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: ${KINTO_PORT}
        resources:
          requests:
            cpu: ${KINTO_RESOURCE_CPU_REQUEST}
            memory: ${KINTO_RESOURCE_MEMORY_REQUEST}
          limits:
            cpu: ${KINTO_RESOURCE_CPU_LIMIT}
            memory: ${KINTO_RESOURCE_MEMORY_LIMIT}
        env:
          - name: PGSSLMODE
            value: "require"
          - name: KINTO_CACHE_BACKEND
            value: "kinto.core.cache.memcached"
          - name: KINTO_CACHE_HOSTS
            value: "cache${BRANCH_HASH}:${MEMCACHED_PORT} cache${BRANCH_HASH}:${MEMCACHED_PORT}"
          - name: KINTO_STORAGE_BACKEND
            value: "kinto.core.storage.postgresql"
          - name: KINTO_STORAGE_URL
            value: "postgresql://${PG_USER_ENCODED}:${PG_PASSWORD_ENCODED}@${PG_HOST}/postgres"
          - name: KINTO_PERMISSION_BACKEND
            value: "kinto.core.permission.postgresql"
          - name: KINTO_PERMISSION_URL
            value: "postgresql://${PG_USER_ENCODED}:${PG_PASSWORD_ENCODED}@${PG_HOST}/postgres"
      initContainers:
      - name: wait-for-postgres
        image: postgres:${POSTGRES_JOB_VERSION}
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          retry=120; # 5s * (12 * 10) = 10min
          while ! pg_isready -h ${PG_HOST} > /dev/null 2> /dev/null && [[ $(( retry-- )) -gt 0 ]];
            do
              echo "Waiting for Postgres to go Green ($(( retry )))" ; sleep 5s ; done ;
          echo Ready;
