---
kind: Job
apiVersion: batch/v1
metadata:
  name: init-kinto
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - image: ${CI_REGISTRY_IMAGE}/kinto:${IMAGE_TAG}
          name: ds-aggregator-init-kinto
          env:
            - name: ENVIRONMENT_TYPE
              valueFrom:
                secretKeyRef:
                  name: ds-aggregator-secret
                  key: ENVIRONMENT_TYPE
            - name: KINTO_BASE_URL
              value: "kinto"
            - name: KINTO_LOGIN
              valueFrom:
                secretKeyRef:
                  name: ds-aggregator-secret
                  key: KINTO_LOGIN
            - name: KINTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ds-aggregator-secret
                  key: KINTO_PASSWORD
          resources:
            requests:
              cpu: ${INIT_KINTO_RESOURCE_CPU_REQUEST}
              memory: ${INIT_KINTO_RESOURCE_MEMORY_REQUEST}
            limits:
              cpu: ${INIT_KINTO_RESOURCE_CPU_LIMIT}
              memory: ${INIT_KINTO_RESOURCE_MEMORY_LIMIT}
      restartPolicy: Never
