---
kind: Job
apiVersion: batch/v1
metadata:
  name: init-kinto
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - image: ${CI_REGISTRY_IMAGE}/kinto:${IMAGE_TAG}
          name: ds-aggregator-init-kinto
          env:
            - name: ENVIRONMENT_TYPE
              valueFrom:
                secretKeyRef:
                  name: ds-aggregator-secret
                  key: ENVIRONMENT_TYPE
            - name: KINTO_BASE_URL
              value: "kinto"
            - name: DS-AGGREGATOR_PG_USER
              value: ${DS_AGGREGATOR_PG_USER}
            - name: DS-AGGREGATOR_PG_PASSWORD
              value: ${DS_AGGREGATOR_PG_PASSWORD}
          resources:
            requests:
              cpu: ${INIT_KINTO_RESOURCE_CPU_REQUEST}
              memory: ${INIT_KINTO_RESOURCE_MEMORY_REQUEST}
            limits:
              cpu: ${INIT_KINTO_RESOURCE_CPU_LIMIT}
              memory: ${INIT_KINTO_RESOURCE_MEMORY_LIMIT}
      restartPolicy: Never
      initContainers:
        - name: wait-for-kinto
          image: registry.gitlab.factory.social.gouv.fr/socialgouv/docker/curl:1.12.0
          imagePullPolicy: Always
          env:
            - name: API_URL
              value: "kinto"
          command:
            - sh
            - -c
            - |
              retry=300; # (60 x 1s) x 5min
              while
                ! curl -sSL "http://${API_URL}:8888/__lbheartbeat__" &&
                [[ $(( retry-- )) -gt 0 ]];
              do echo "Waiting for ${API_URL} to be available ($(( retry )))" ; sleep 1s ; done ;
              [[ $(( retry )) -lt 1 ]] && exit 128;
              echo Ready;
