---
apiVersion: v1
kind: Service
metadata:
  name: kinto
  labels:
    app: ${PROJECT}
    component: kinto
    namespace: ${PROJECT}-${BRANCH_HASH}
spec:
  selector:
    component: kinto
  ports:
    - port: ${KINTO_PORT}
      name: kinto
