---
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_VERSION: "18.06"
  API_PORT: 1337

stages:
- "Prepare"
- "Registration"


###########################################
###       REGISTER DOCKER IMAGES        ###
###########################################

#
.register_stage: &register_stage
  stage: "Registration"
  image: docker:$DOCKER_VERSION
  services:
  - docker:$DOCKER_VERSION-dind
  before_script:
  - echo "$CI_JOB_TOKEN" | docker login $CI_REGISTRY -u gitlab-ci-token --password-stdin
  - docker pull $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA || true
  script:
  - echo "Build $IMAGE_NAME:$CI_COMMIT_SHA from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA"
  - docker build --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA -t $IMAGE_NAME:$CI_COMMIT_SHA -f $DOCKERFILE_PATH $CONTEXT
  - docker push $IMAGE_NAME
#

Register ds-collector image:
  <<: *register_stage
  variables:
    CONTEXT: .
    DOCKERFILE_PATH: packages/ds-collector/Dockerfile
    IMAGE_NAME: $CI_REGISTRY_IMAGE/ds-collector

