---
dist: xenial
language: minimal
git:
  depth: 5

jobs:
  include:
    - stage: Build
      language: node_js
      node_js: stable
      cache: yarn
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      script:
        - yarn build
        - yarn lint
        - yarn test
      after_script:
        - npx codecov
