---
version: "3.5"

services:
  ds-aggregator-api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
      shm_size: 256M
    env_file: .env
    ports:
      - 4000:4000

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ds-aggregator-pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  ds-aggregator-pgdata:
