---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ds-aggregator-api${HASH_BRANCH_NAME}
  labels:
    app: ds-aggregator-api${HASH_BRANCH_NAME}
    branch: ds-aggregator${HASH_BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-aggregator-api${HASH_BRANCH_NAME}
  template:
    metadata:
      labels:
        app: ds-aggregator-api${HASH_BRANCH_NAME}
    spec:
      containers:
        - image: ${DS_AGGREGATOR_REGISTRY}/api:${IMAGE_TAG}
          name: ds-aggregator-api
          ports:
            - containerPort: ${PORT}
          env:
            - name: ENVIRONMENT_TYPE
              valueFrom:
                secretKeyRef:
                  name: ds-aggregator-secret
                  key: ENVIRONMENT_TYPE
            - name: API_PORT
              value: "${PORT}"
            - name: API_PREFIX
              valueFrom:
                secretKeyRef:
                  name: ds-aggregator-secret
                  key: API_PREFIX
            - name: KINTO_URL
              value: "http://kinto${HASH_BRANCH_NAME}:8888"
            - name: KINTO_LOGIN
              valueFrom:
                secretKeyRef:
                  name: ds-aggregator-secret
                  key: KINTO_LOGIN
            - name: KINTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ds-aggregator-secret
                  key: KINTO_PASSWORD
            - name: DS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ds-aggregator-secret
                  key: DS_TOKEN
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: ds-aggregator-secret
                  key: SENTRY_DSN
