# See https://github.com/SocialGouv/helm-charts/tree/master/charts/app

image:
  repository: ${CI_REGISTRY_IMAGE}/api
  tag: ${IMAGE_TAG}

deployment:
  livenessProbe:
    path: /api/liveness
    initialDelaySeconds: 20
    periodSeconds: 10

  readinessProbe:
    path: /api/readiness
    initialDelaySeconds: 20
    periodSeconds: 10

  resources:
    requests:
      cpu: 500m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 256Mi
  envFrom:
    - secretRef:
        name: ds-aggregator-secret
  env:
    - name: API_PORT
      value: "${PORT}"
    - name: KINTO_URL
      value: "http://kinto:8888"

ingress:
  enabled: true
