apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: api-env
spec:
  encryptedData:
    API_PREFIX: AgB7Wc5rNuVjPDFkvOXOZY2yehZkwMMYP1WZrEBjkuol5PDczAXWH6vtDS7XC8PTxjqB8f1tUKki4kv4a39Zz8TsfzSAeOJKsZP1Uy5+sDuN1tkPNbPAXdJ4YpI0FuBRovgkRq651pMpJVk1Aho/MMwmNgxb08iCB++xF4nTFy3EyAoLdZqWLnhGH3STOrMShrwt0wNcVImjSbiabF1RdblXW60nhUKLV/f+gxIpzzFiJiovW4nm0TrNRGNoUjMgjfLAGL/udacop3IH20hcJ5fdrQmzAkYIqVjs31X0lil7lBQsn1gcfpAC/HBTSzdqx+WVul+8Vyyv67ZNPwyJFoAEohH7CH1Ow73utkAlUgCisChVcahgYs/pfkeyaOJFqhTpvPH75U8i0DgfMnZuDfUnqXEwesfLzAugl0dYL9QlvAcQZWvTSBBNYOvJuaSqdlmOX+u28bdCosviIA8ZN6ccKuJLQaXvMFtQMzmyR55N5Qn7V5lBo5zyx7POWcV3yAcQe2qR4KjxkfdWimVzEGwSIWkISXTbkQ2Lb50kGk1A8gYDevjVHApZ4TkQV8dCi5xJvzwWUWdG52ZgTAWc8YQx3/PRzH9lOMAm0QnR7w1n/H9dYzOrs6OgllF2+Z+H4JMy/dIDvNICmJcqqpdJVBoS5oYQnw9z8BywOIwsT9A0AbIiy3DzHy6M5YagdsMstfNm6h0EMGdAGNXxM3Qwbk5l
    DATABASE_URL: AgAcF1qc0O4XzZh+lltfqphSqx3x9hsyDVhmdRpi7KqiaseeKMK7C00T+ty4teRw6Cdd7Mu9ix0a5ZRb1DiYIJaaiCYAurnJzyAM2OlEmPaoB7tQZf/Zps8qzc0vKDdD0qX9MNVTRG2Dgp+UzHUViIlQN7/A+uuBE0k3osCO/S2HmLvkHmYTa+VfgebJcbLa6Gmq/HS6Xb0/As4MHUdZXHA9xJhj+nWCW2R44RUUjkwkSwP79tMymh5qpctPHrndvBhhNjzR0j8XSHA9A21tHXONfqEM6VEEs+tq73h7+TlPPUrHO0O4brdKs1QdjR2Tu7naRvEnbN779w9SIObcRyKjLtQ08c18TYtCn52VNB7DJfL5Fzh3e9IBbHI41qQ8UjkyyVRjgHsA3UJL66eiyn6Ll0wZ/KilM1iTJC3VDioinvJrImpEdvadELiWYwwgWvl/8igkfvBzQ6o0GMeBQ/386XpwRkEqQDSFcu/gdCuZcNSyAFrUszvB9pNPp16NDlxglkVqdbzLrkYN+MOoxPUiwrNvUMBPflbTntphke8t3IkrIs2J31xYjqC+k/h6zGU9kUFlLT5dh5fJMh8N1RF+H1wZlhX9TGe1UQAlT/ZqOpQShBd5n+hX4/qV1G9JhOWwcjusxU/I5K3so8L3krijUxcHrddNAQMvbBCRHDXgtYx0P/lTJ5+Wgbc7fZdcR/nkQEj3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: api-env
    type: Opaque
