---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cache${HASH_BRANCH_NAME}
  labels:
    app: cache${HASH_BRANCH_NAME}
    branch: ds-aggregator${HASH_BRANCH_NAME}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cache${HASH_BRANCH_NAME}
        branch: ds-aggregator${HASH_BRANCH_NAME}
    spec:
      containers:
      - name: cache
        image: library/memcached:1.5
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: ${PORT}
