---
apiVersion: v1
kind: Service
metadata:
  name: cache${HASH_BRANCH_NAME}
  labels:
    app: cache${HASH_BRANCH_NAME}
    branch: ds-aggregator${HASH_BRANCH_NAME}
spec:
  type: NodePort
  ports:
  - port: ${PORT}
  selector:
    app: cache${HASH_BRANCH_NAME}
