#!/bin/bash

if [[ -z "${DS_TOKEN}" ]]; then
  echo "Expect DS_TOKEN to be defined";
  exit 1;
fi

echo -n "${DS_TOKEN}" \
  | parallel --pipe --tee -v {} ::: \
    "sealed_as api-env ${0} --scope cluster-wide"
